anchor_version = "0.20.1"
solana_version = "1.9.0"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "devnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_token_manager = "mgrMbgLbusR19KEKMa9WsYDAeL94Tavgc9JHRB1CCGz"
cardinal_payment_manager = "cpmTAQfUopUzqu2BAR5EfnUfqJSgZkMoU7QBvkueyEn"
cardinal_paid_claim_approver = "pcaQ9jQLzb8VszyM6oPRoiGsdjizxMyvGjauhKPD5EF"
cardinal_time_invalidator = "tmexpMz3HojAQ4i97rgaJYhPHM9hV6AzWmQ7EprRPGe"
cardinal_rental_counter = "cntQPZbfxBeLa8HVBbA4fApyAKh8mUxUVeaCjBLFSFP"

[programs.devnet]
cardinal_token_manager = "mgrMbgLbusR19KEKMa9WsYDAeL94Tavgc9JHRB1CCGz"
cardinal_payment_manager = "cpmTAQfUopUzqu2BAR5EfnUfqJSgZkMoU7QBvkueyEn"
cardinal_paid_claim_approver = "pcaQ9jQLzb8VszyM6oPRoiGsdjizxMyvGjauhKPD5EF"
cardinal_time_invalidator = "tmexpMz3HojAQ4i97rgaJYhPHM9hV6AzWmQ7EprRPGe"
cardinal_rental_counter = "cntQPZbfxBeLa8HVBbA4fApyAKh8mUxUVeaCjBLFSFP"

[programs.testnet]
cardinal_token_manager = "mgrMbgLbusR19KEKMa9WsYDAeL94Tavgc9JHRB1CCGz"
cardinal_payment_manager = "cpmTAQfUopUzqu2BAR5EfnUfqJSgZkMoU7QBvkueyEn"
cardinal_paid_claim_approver = "pcaQ9jQLzb8VszyM6oPRoiGsdjizxMyvGjauhKPD5EF"
cardinal_time_invalidator = "tmexpMz3HojAQ4i97rgaJYhPHM9hV6AzWmQ7EprRPGe"
cardinal_rental_counter = "cntQPZbfxBeLa8HVBbA4fApyAKh8mUxUVeaCjBLFSFP"

[programs.localnet]
cardinal_token_manager = "mgrMbgLbusR19KEKMa9WsYDAeL94Tavgc9JHRB1CCGz"
cardinal_payment_manager = "cpmTAQfUopUzqu2BAR5EfnUfqJSgZkMoU7QBvkueyEn"
cardinal_paid_claim_approver = "pcaQ9jQLzb8VszyM6oPRoiGsdjizxMyvGjauhKPD5EF"
cardinal_time_invalidator = "tmexpMz3HojAQ4i97rgaJYhPHM9hV6AzWmQ7EprRPGe"
cardinal_rental_counter = "cntQPZbfxBeLa8HVBbA4fApyAKh8mUxUVeaCjBLFSFP"
