anchor_version = "0.20.1"
solana_version = "1.9.0"

[scripts]
test = "yarn mocha tests/claimLinks.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_receipt_index = "rcpCr9GVsP2CPmS11uuFXUXbzc5JJQFMDvDRn8JDQNh"

[programs.devnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_receipt_index = "rcpCr9GVsP2CPmS11uuFXUXbzc5JJQFMDvDRn8JDQNh"

[programs.testnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_receipt_index = "rcpCr9GVsP2CPmS11uuFXUXbzc5JJQFMDvDRn8JDQNh"

[programs.localnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_receipt_index = "rcpCr9GVsP2CPmS11uuFXUXbzc5JJQFMDvDRn8JDQNh"
