anchor_version = "0.24.2"
solana_version = "1.10.30"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
solana_nft_programs_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
solana_nft_programs_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
solana_nft_programs_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
solana_nft_programs_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
solana_nft_programs_transfer_authority = 'trsMRg3GzFSNgC3tdhbuKUES8YvGtUBbzp5fjxLtVQW'

[programs.devnet]
solana_nft_programs_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
solana_nft_programs_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
solana_nft_programs_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
solana_nft_programs_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
solana_nft_programs_transfer_authority = 'trsMRg3GzFSNgC3tdhbuKUES8YvGtUBbzp5fjxLtVQW'

[programs.testnet]
solana_nft_programs_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
solana_nft_programs_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
solana_nft_programs_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
solana_nft_programs_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
solana_nft_programs_transfer_authority = 'trsMRg3GzFSNgC3tdhbuKUES8YvGtUBbzp5fjxLtVQW'

[programs.localnet]
solana_nft_programs_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
solana_nft_programs_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
solana_nft_programs_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
solana_nft_programs_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
solana_nft_programs_transfer_authority = 'trsMRg3GzFSNgC3tdhbuKUES8YvGtUBbzp5fjxLtVQW'
